name: pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -la docs
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages
